### ISSUE TITLE
GlycoSphingolipid type

### ISSUE THREAD

**Issue by ReneRanzinger** [glygen-glycan-data/PyGly#37]
For GlyGen we should add a class GlycoSphingolipid with the following Subclasses. All motifs have to be at the reducing end of the glyan and can be extended:

- [Mollu series](https://glycomotif.glyomics.org/glycomotif/GTC.G00015MO)
![Mollu](https://image.glycosmos.org/snfg/png/G00015MO)
- [Gala series](https://glycomotif.glyomics.org/glycomotif/GTC.G00016MO)
![Gala](https://image.glycosmos.org/snfg/png/G00016MO)
- [Arthro series](https://glycomotif.glyomics.org/glycomotif/GTC.G00014MO)
![Arthro](https://image.glycosmos.org/snfg/png/G00014MO)
- [Muco series](https://glycomotif.glyomics.org/glycomotif/GTC.G00013MO)
![Muco](https://image.glycosmos.org/snfg/png/G00013MO)
- [Isoglobo series](https://glycomotif.glyomics.org/glycomotif/GTC.G00012MO)
![Iso-Globo](https://image.glycosmos.org/snfg/png/G00012MO)
- [Neo-lacto series](https://glycomotif.glyomics.org/glycomotif/GTC.G00070MO)
![Neo-Lacto](https://image.glycosmos.org/snfg/png/G00070MO)
- [Ganglio series](https://glycomotif.glyomics.org/glycomotif/GTC.G00071MO)
![Ganglio](https://image.glycosmos.org/snfg/png/G00071MO)
- [Globo series](https://glycomotif.glyomics.org/glycomotif/GTC.G00072MO)
![Globo](https://image.glycosmos.org/snfg/png/G00072MO)
- [Lacto series](https://glycomotif.glyomics.org/glycomotif/GTC.G00069MO)
![Lacto](https://image.glycosmos.org/snfg/png/G00069MO)

**Comment by mtiemeyer0919** [comment]
Goboseries should be Gala4Gal not Galb4Gal

Mollu and Arthro series won't be a thing until we incorporate marine invertebrates and insect structures

**Comment by edwardsnj** [comment]
I've added these to the GlyGen classification motif set. @mtiemeyer0919: You suggested change would make Isoglobo and Globo series identical: 

Isoglobo: https://glycomotif.glyomics.org/glycomotif/GTC.G00012MO 

Globo: https://glycomotif.glyomics.org/glycomotif/GTC.G00072MO

Are you sure we need to change the Globo series core?

**Comment by edwardsnj** [comment]
Argh. I'm wrong, the isoglobo series are a3 not a4. I'll change the globo series core.

**Comment by mtiemeyer0919** [comment]
I like a person who can admit they are wrong!

Cheers,
MikeT


-------------------------
Michael Tiemeyer
Distinguished Research Professor and Co-Director
Complex Carbohydrate Research Center and
The Department of Biochemistry and Molecular Biology
University of Georgia
315 Riverbend Rd.
Athens, GA  30602
706-542-2740  Office
706-542-4412  FAX
mtiemeyer@ccrc.uga.edu
http://cell.ccrc.uga.edu/~mtiemeyer/


________________________________

**Comment by edwardsnj** [comment]
These are implemented in GlycoMotif and as classifications in GlycanData. See them here:

https://edwardslab.bmcb.georgetown.edu/glycandatadev/Glycosphingolipid_Classification

A link to the glycomotif motifs is provided there too.

**Comment by ReneRanzinger** [comment]
I need to confirm with Mike regarding the branching pattern for Mullo series (e.g. G09603GS, G12794OB, G16860QL, G23126YQ)

@edwardsnj : Is there a reason that the Lacto series is missing? I also think we can try your proposal and use Gal-(1-4)-Glc as classifier for GSL with no subtype.

**Comment by edwardsnj** [comment]
On 2/1/2021 3:55 PM, Rene Ranzinger wrote:
> I need to confirm with Mike regarding the branching pattern for Mullo 
> series (e.g. G09603GS, G12794OB, G16860QL, G23126YQ)
> 
> @edwardsnj <https://github.com/edwardsnj> : Is there a reason that the 
> Lacto series is missing? I also think we can try your proposal and use 
> Gal-(1-4)-Glc as classifier for GSL with no subtype.

Thanks for catching the missing lacto series in the GlycanData page.

- n

**Comment by edwardsnj** [comment]
See this site for a list of added or removed subtypes, including Glycosphingolipid subtypes, in the next release:

   http://edwardslab.bmcb.georgetown.edu/~nedwards/dropbox/5SCrtrAXjf/
