### ISSUE TITLE
GAG type

### ISSUE THREAD

**Issue by ReneRanzinger** [glygen-glycan-data/PyGly#38]
Here is a description of the GAG classifier. Its not going to be easy to implement it with the current infrastructure.

1. A GAG is a linear sugar consisting of two types of monosaccharides that follow in alternating sequence
   - Type 1: HexNAc residue (can be GlcNAc or GalNAc) or HexNS (can be Glc or Gal)
   - Type 2: HexA residue (can be GlcA or IdoA)
2. The exception to 1. is Keratansulfate where Type 2 is a Gal
3. The sequence of monosaccharide can have an arbitrary length from 2 monosaccharides up. Its also possible that the sequence has a odd number of monosaccharides.
4. The sequence may or may not be part of a repeat unit or be represented as oligosaccharide.
5. If the terminal monosaccharide is an acidic monosaccharide it may have been converted into a deltaUA (HexA with a 4-5 double bond)
G01825JS
![1](https://image.glycosmos.org/snfg/png/G01825JS)
6. The monosaccarides of one type may be different across the sequence (e.g. first MS is a GlcNAc but third MS is a GlcNS; second MS is a GlcA but forth is a IdoA)
7. Monosaccarides can be decorated on any free hydroxyl group with a sulfate. This sulfation pattern may also change even within a type along the sequence (e.g. first monosaccharide has no sulfate, third monosaccahride has 2 sulfates.

**Comment by edwardsnj** [comment]
Initial GAG type and subtype logic implemented based on the work to support repeat units in structure with motif alignments. Considerable work from Rene and Mike to help define acceptable GAGs. This is a work in progress, but this is a good first effort.
