### ISSUE TITLE
NGlycan: unknown linkage and anomer

### ISSUE THREAD

**Issue by ReneRanzinger** [glygen-glycan-data/PyGly#39]
N-Glycans that have missing linkage information or anomer should still be classified as such. Examples are the following IDs:

G02420CD
![1](https://image.glycosmos.org/snfg/png/G02420CD)
G45583CF
![2](https://image.glycosmos.org/snfg/png/G45583CF)
G00207YQ
![3](https://image.glycosmos.org/snfg/png/G00207YQ)
G00396DP
![4](https://image.glycosmos.org/snfg/png/G00396DP)
G00488OU
![5](https://image.glycosmos.org/snfg/png/G00488OU)

Special cases are Glycans where only some linkages or anomers are missing:
G31249TS
![6](https://image.glycosmos.org/snfg/png/G31249TS)

This will affect hundreds if not thousands of structures.

**Comment by edwardsnj** [comment]
Anomeric and linkage information can be ignored by setting the motif anomeric and linkage information to ?. However, I suspect that the logic applied to linkage (not inconsistent with), see [Glycosidic Bond Comparison](https://glycomotif.glyomics.org/glycomotif/Glycan_Core_Alignment#Glycosidic_Bond_Comparison) rule 4 might be better here applied to anomers and ring information too - compatible, not equal, so that when a strange or unlikely anomer is specified, is it not matched with a motif wildcard.

**Comment by edwardsnj** [comment]
Should [G32708SB](http://gnome.glyomics.org/StructureBrowser.html?focus=G32708SB) (3 linkage in core) or [G26835MN](http://gnome.glyomics.org/StructureBrowser.html?focus=G26835MN) (alpha anomer in core) be considered N-glycans?

**Comment by ReneRanzinger** [comment]
Setting the anomer, ring and linkage in the motif to ? is not a good idea since that would lead to many false positives. Examples are the IDs you mentioned G32708SB and G26835MN. 

Better solution would be a specialized alignment algorithm for glycan types that takes a defined linkage and anomer gives a match if the information matches perfectly or the queried structure has unknown (? or -1) in that place.  Rule 4 mentioned above would work for linkages but similar parts would be needed for ring and anomer. But this alignment should only be used for the glycan type but not for the motif match.

**Comment by mtiemeyer0919** [comment]
GlcNAcb3GlcNAc and GlcNAc alpha to anything are both never, never in the chitobiose core, which is conserved across all animals and most plants.  They are lies. 
http://gnome.glyomics.org/StructureBrowser.html?focus=G32708SB
http://gnome.glyomics.org/StructureBrowser.html?focus=G26835MN

**Comment by edwardsnj** [comment]
Revised motif matching logic does not permit structures that specify only values that do not match the motif.

So G26835MN is not considered an N-glycan, 

https://edwardslab.bmcb.georgetown.edu/glycandatadev/G26835MN#Classification

but otherwise, unknown linkage and anomer is now being handled.

**Comment by ReneRanzinger** [comment]
@edwardsnj  For this kind of problem it would be nice to have a page with the delta that was generated by applying this new rule. Or a comma separated list of GlyTouCan IDs. Otherwise we can close this ticket.

**Comment by edwardsnj** [comment]
See this site for a list of added or removed subtypes, including N-glycan subtypes, in the next release:

   http://edwardslab.bmcb.georgetown.edu/~nedwards/dropbox/5SCrtrAXjf/
