### ISSUE TITLE
NGlycan: Reduced

### ISSUE THREAD

**Issue by ReneRanzinger** [glygen-glycan-data/PyGly#40]
If the NGlycan was reduced in the release (converted into alditol) it should still be detected as such. Examples are:

G88227HW
![1](https://image.glycosmos.org/snfg/png/G88227HW)
G00706AL
![2](https://image.glycosmos.org/snfg/png/G00706AL)

There are combinations of this problem and #39 :

G00331XG
![3](https://image.glycosmos.org/snfg/png/G00331XG)
G42710BN
![4](https://image.glycosmos.org/snfg/png/G42710BN)
G00381YD
![5](https://image.glycosmos.org/snfg/png/G00381YD)

**Comment by edwardsnj** [comment]
This will be solved by the new alignment semantics (which permits an unspecified aditol at the reducing end of the matched structure). See: [GlycoMotif Glycan Core Alignment](https://glycomotif.glyomics.org/glycomotif/Glycan_Core_Alignment). As the new GlycoMotif alignment semantics move into the GlycanData build, they will allow the top two to be categorized as N-linked by [GGM.001001](https://glycomotif.glyomics.org/glycomotif/GGM.001001) and related motifs. The remainder can be treated as for #39.

**Comment by edwardsnj** [comment]
New non-strict alignments used for classification tolerate additional alditol and/or uncyclized ring/anomer information in matching classification motifs. These are now matched. See:

  https://edwardslab.bmcb.georgetown.edu/glycandatadev/G00331XG#Classification

**Comment by ReneRanzinger** [comment]
@edwardsnj For this kind of problem it would be nice to have a page with the delta that was generated by applying this new rule. Or a comma separated list of GlyTouCan IDs. Otherwise we can close this ticket.

**Comment by edwardsnj** [comment]
See this site for a list of added or removed subtypes, including N-glycan subtypes, in the next release:

   http://edwardslab.bmcb.georgetown.edu/~nedwards/dropbox/5SCrtrAXjf/
