### ISSUE TITLE
NGlycan subtype: missing linkages

### ISSUE THREAD

**Issue by ReneRanzinger** [glygen-glycan-data/PyGly#42]
If anomer/linkage information is missing or incomplete at the Nglycan core the glycan should still be classified as complex or hybrid:
G00231IQ - hybrid
![1](https://image.glycosmos.org/snfg/png/G00231IQ)

G00281HB - hybrid
![2](https://image.glycosmos.org/snfg/png/G00281HB)

G00318AV - complex
![3](https://image.glycosmos.org/snfg/png/G00318AV)

G00328CG - complex
![4](https://image.glycosmos.org/snfg/png/G00328CG)

G00396IE - complex
![5](https://image.glycosmos.org/snfg/png/G00396IE)

**Comment by edwardsnj** [comment]
This is already the case for linkage position, but not for anomeric configuration. Again, the question becomes, anything goes, or specific unexpected values recognized and alignment blocked.

**Comment by ReneRanzinger** [comment]
See [comment ](https://github.com/glygen-glycan-data/PyGly/issues/39#issuecomment-728739731) on the other ticket.

**Comment by edwardsnj** [comment]
@ReneRanzinger Clarification on G00396IE  - one arm has 6-linkage on the GlcNAc. Complex motif only [GGM.001004](https://glycomotif.glyomics.org/glycomotif/GGM.001004) permits 2 or 4 on this linkage, hence this is not considered a motif match even under our expanded matching rules. Does this mean you would like to expand the possible linkages considered valid for complex N-glycans?

**Comment by ReneRanzinger** [comment]
@edwardsnj good point. I was not careful enough here. As far as I know the 6 arm gets added after the 2,4. But lets confirm that with @mtiemeyer0919.

**Comment by mtiemeyer0919** [comment]
Yes.  Rene is correct.  GlcNAc can't be added to the 6 position of the Manalpha6 arm until it has already been added to the 2 position.  MGAT5, the enzyme that adds the 6-GlcNAc uses the 2-GlcNAc for recognition of substrate

**Comment by edwardsnj** [comment]
This has been implemented, see the new classifications here:

  https://edwardslab.bmcb.georgetown.edu/glycandatadev/Main_Page

**Comment by ReneRanzinger** [comment]
@edwardsnj For this kind of problem it would be nice to have a page with the delta that was generated by applying this new rule. Or a comma separated list of GlyTouCan IDs. Otherwise we can close this ticket.

**Comment by edwardsnj** [comment]
See this site for a list of added or removed subtypes, including N-glycan subtyes, in the next release:

   http://edwardslab.bmcb.georgetown.edu/~nedwards/dropbox/5SCrtrAXjf/
