### ISSUE TITLE
Glycan composition

### ISSUE THREAD

**Issue by ReneRanzinger** [glygen-glycan-data/PyGly#43]
After talking with Mike we came to the decision that we would like to assign glycan types to compositions as well. We could use subsumption to assign these. Problem is that in this case a glycan can have multiple types (e.g. same composition can come from N-Glycans AND O-Glycans). Its also possible that one glycan can be assigned multiple sub-types.

**Comment by edwardsnj** [comment]
We apply both subsumption and non-strict alignment to ensure that classification motifs are applied to compositions. See the new classifications here:

  https://edwardslab.bmcb.georgetown.edu/glycandatadev/Main_Page
