### ISSUE TITLE
NGlycan truncated

### ISSUE THREAD

**Issue by ReneRanzinger** [glygen-glycan-data/PyGly#45]
There are several cases of NGlycans that are missing the reducing end GlcNAc. This can happen either as an artefact of the analysis, a degradation product when recycling GlycoProteins or as part of some disease. We should assign them the Type "NGlycan" but put them into a "truncated" subtype box.

G64399AZ
![1](https://image.glycosmos.org/snfg/png/G64399AZ)

G00060BT
![1](https://image.glycosmos.org/snfg/png/G00060BT)

G02173JB
![1](https://image.glycosmos.org/snfg/png/G02173JB)

**Comment by edwardsnj** [comment]
I have added a new core-motif to the glygen classification motif set to match truncated N-glycans.

**Comment by edwardsnj** [comment]
See the new list of N-linked glycan subtypes, including truncated glycans here:

  https://edwardslab.bmcb.georgetown.edu/glycandatadev/N-Glycan_Classification

**Comment by ReneRanzinger** [comment]
@edwardsnj For this kind of problem it would be nice to have a page with the delta that was generated by applying this new rule. Or a comma separated list of GlyTouCan IDs. Otherwise we can close this ticket.

**Comment by edwardsnj** [comment]
See these files for a list of added or removed subtypes, including N-glycan truncated, in the next release:

   http://edwardslab.bmcb.georgetown.edu/~nedwards/dropbox/5SCrtrAXjf/
