### ISSUE TITLE
Superclass NGlycans

### ISSUE THREAD

**Issue by ReneRanzinger** [glygen-glycan-data/PyGly#50]
This should be NGlycans as well:
G12683MU
![1](https://image.glycosmos.org/snfg/png/G12683MU)

G00633PX
![1](https://image.glycosmos.org/snfg/png/G00633PX)

G04341AI
![1](https://image.glycosmos.org/snfg/png/G04341AI)

G08639EI
![1](https://image.glycosmos.org/snfg/png/G08639EI)

G06359BI
![1](https://image.glycosmos.org/snfg/png/G06359BI)

G01357WC
![1](https://image.glycosmos.org/snfg/png/G01357WC)

G05242GV
![1](https://image.glycosmos.org/snfg/png/G05242GV)

G04094WJ
![1](https://image.glycosmos.org/snfg/png/G04094WJ)

**Comment by edwardsnj** [comment]
Our current motif matching logic does not apply the same missing information logic to stem/config information as it does to anomer, ring, etc. information. These would be picked up by subsumption if there were anything appropriate below them in the subsumption hierarchy, so there must not be much below them. We could allow our motif matching logic to match these, just not convinced it is a great idea...

**Comment by ReneRanzinger** [comment]
I would only do this for N-glycans. Since its unlikely that the HexNAc2Hex3 core would cause many false positive. For the other classes (O, GSL) I would not do this. Maybe we can try this first and look at the delta before making it live. If that is to much overhead I would give it low priority.

**Comment by edwardsnj** [comment]
This was added to GlycoMotif with expanded matching logic and is has been available since GlyGen-GlycanData-Export-v1.9.0.
