### ISSUE TITLE
GPI Anchor class

### ISSUE THREAD

**Issue by ReneRanzinger** [glygen-glycan-data/PyGly#51]
Add a new class for GPI Anchors. There wont be many, probably just a few dozen. 

G46392BZ
![1](https://image.glycosmos.org/snfg/png/G46392BZ)

This is the core at the reducing end. The mannose residues can be extended by other monosacharides or subsituent:

https://www.sigmaaldrich.com/content/dam/sigma-aldrich/articles/biology/Glycobiology/structure-of-gpi-anchored-proteins.jpg

**Comment by edwardsnj** [comment]
This was added to GlycoMotif and is now available in GlyGen-GlycanData-Export-v1.10.0.
