### ISSUE TITLE
O-GlcNac type

### ISSUE THREAD

**Issue by ReneRanzinger** [glygen-glycan-data/PyGly#55]
A new subtype for O-Glycans. Conists of a single monosaccharide and should capture:

G49108TO
![1](https://image.glycosmos.org/snfg/png/G49108TO)

G64581RP
![2](https://image.glycosmos.org/snfg/png/G64581RP)

a-D-GlcNAc should not be part of this. We should confirm with @mtiemeyer0919 if we also want to capture the following structures that miss complete or partial ring size information:

G14843DJ
![3](https://image.glycosmos.org/snfg/png/G14843DJ)

G86089ZC
![4](https://image.glycosmos.org/snfg/png/G86089ZC)

**Comment by edwardsnj** [comment]
This was added to GlycoMotif and is now available in GlyGen-GlycanData-Export-v1.10.0.
